doctrine_migrations:
    migrations_paths:
        'App\Resources\Migrations': '%kernel.project_dir%/src/Resources/Migrations'
    enable_profiler: '%kernel.debug%'
    services:
        # add factories / services for your migrations here
        # if you really want to use the entity manager, add a Migration FactoryOverride, like this:
        #'Doctrine\Migrations\Version\MigrationFactory': 'App\Resources\Factories\MigrationFactoryDecorator'
