somnambulist_api:
    exception_handler:
        converters:
            Assert\InvalidArgumentException: Somnambulist\Bundles\ApiBundle\Services\Converters\AssertionExceptionConverter
            Assert\LazyAssertionException: Somnambulist\Bundles\ApiBundle\Services\Converters\LazyAssertionExceptionConverter
            Symfony\Component\Messenger\Exception\HandlerFailedException: Somnambulist\Bundles\ApiBundle\Services\Converters\HandlerFailedExceptionConverter
    request_handler:
        per_page: 20
        max_per_page: 100
        limit: 100
        request_id_header: 'X-Request-Id'
    subscribers:
        exception_to_json: true
        json_to_post: true
        request_id: true
    openapi:
        version: '1.0.0'
        title: 'API Skeleton Service'
        description: 'API documentation for the skeleton service.'

somnambulist_form_request:
    subscribers:
        authorization: true
        form_validation: true

somnambulist_read_models:
    connections:
        'default': 'doctrine.dbal.default_connection'
    subscribers:
        request_manager_clearer: true
        messenger_manager_clearer: true
