version: '3'

services:
  app:
    build:
      context: .
      dockerfile: src/Resources/docker/prod/app/Dockerfile
    networks:
      - example_network

networks:
  example_network:
    external: true
