version: '3.7'

services:
  api-app:
    build:
      context: .
      dockerfile: config/docker/dev/app/Dockerfile
    networks:
      - mycompany_network_backend
    labels:
      traefik.enable: true
      traefik.http.routers.api-app.rule: "Host(`app.example.dev`)"
      traefik.http.routers.api-app.tls: true
      traefik.http.services.api-app.loadbalancer.server.port: 8080

  app-redis:
    image: redis:alpine
    networks:
      - mycompany_network_backend

networks:
  mycompany_network_backend:
    external: true
